"""
Round-1 revision -- regenerate manuscript Figure 14 (fig:mi_by_gage) with Spanish
Fork (gage 10152000) dropped entirely.

Same advisor decision as round1_gslb_figures_no_spanish_fork.py: the letter to
Reviewer 1 says Spanish Fork is now reported only once, but the MI-by-gage boxplot
(generated by the pipeline's generic gwbase.plot_mi_results(), which plots whatever
gages are present in mi_results with no filtering) still showed all five gages.
Reproduces that boxplot exactly, filtered to the four retained catchments.

Run:  ./.venv/bin/python notebooks/round1_mi_by_gage_no_spanish_fork.py
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

BASE    = Path(__file__).parent.parent
RESULTS = BASE / "results"
OUT_DIR = RESULTS / "round1_revision" / "10_mi_by_gage_no_spanish_fork"
OUT_DIR.mkdir(parents=True, exist_ok=True)

SPANISH_FORK = 10152000

BASIN_NAMES = {
    '10126000': 'Bear River',
    '10141000': 'Weber River',
    '10163000': 'Provo River',
    '10168000': 'Little Cottonwood',
}

mi_results = pd.read_csv(RESULTS / "features" / "mi_analysis.csv")
mi_results = mi_results[mi_results["gage_id"] != SPANISH_FORK].copy()
print(f"Retained gages: {sorted(mi_results['gage_id'].unique())}")
print(f"n well-gage pairs after dropping Spanish Fork: {len(mi_results)}")

plot_df = mi_results.copy()
plot_df['_gage_label'] = plot_df['gage_id'].astype(str).map(
    lambda g: BASIN_NAMES.get(g, g)
)
# Order by gage_id ascending (Bear, Weber, Provo, Little Cottonwood), matching
# the manuscript's other tables/figures rather than pandas' default
# first-appearance order.
order = [BASIN_NAMES[g] for g in sorted(BASIN_NAMES, key=int)]

plt.figure(figsize=(max(8, plot_df['gage_id'].nunique() * 1.2), 5))
sns.boxplot(data=plot_df, x='_gage_label', y='mi', order=order)
plt.xticks(rotation=45, ha='right')
plt.xlabel('Basin')
plt.ylabel('Mutual Information')
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()

out = OUT_DIR / "mi_by_gage.png"
plt.savefig(out, dpi=600)
plt.close()
print(f"Saved: {out}")

for g, name in BASIN_NAMES.items():
    vals = plot_df[plot_df['gage_id'].astype(str) == g]['mi']
    print(f"  {name:20s} n={len(vals):4d}  median={vals.median():.4f}  IQR=[{vals.quantile(.25):.4f}, {vals.quantile(.75):.4f}]")
